version: '3.9'

services:
  db:
    image: postgres
    container_name: postgres_database
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5433:5433"
    restart: always
    environment:
      - DOCKER=True
      - POSTGRES_DB=testdb
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=senha
      - DB_USER=django
      - DB_PASSWORD=senha
      - DB_DATABASE=testdb
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/restLojinha
    ports:
      - "8080:8080"
    depends_on:
      - db
